version: '3'

services:
  postgres-compose:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "1234567"
    ports:
      - "5432:5432"
    # volumes:
    #   - D:\temp\devsuperior2.0\dsdeliver-sds2\docker\data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234567"
    ports:
      - "9090:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge